name: Render HTML to PDF

on:
  push:
    # trigger on changes to any HTML file (or this workflow)
    paths:
      - '**/*.html'
      - '.github/workflows/render-html-to-pdf.yml'

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Playwright
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          # install browser binaries
          playwright install --with-deps

      - name: Render HTML to PDF
        run: |
          python - <<'EOF'
          import os
          from playwright.sync_api import sync_playwright

          # Adjust these if your HTML lives in a subfolder or has a different name
          html_file = 'index.html'
          pdf_file  = 'rendered.pdf'
          html_path = os.path.abspath(html_file)

          with sync_playwright() as p:
              browser = p.chromium.launch()
              page = browser.new_page()
              # load the local file
              page.goto(f'file://{html_path}')
              # generate PDF
              page.pdf(path=pdf_file, format='A4', print_background=True)
              browser.close()
          EOF

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: rendered-html-pdf
          path: rendered.pdf
